from pprint import pprint
from time import sleep
from selenium.common.exceptions import WebDriverException, StaleElementReferenceException, TimeoutException
from selenium.webdriver import Chrome
import random

from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.support.wait import WebDriverWait

another = [
        "Aaren"
        ,
        "Aarika"
        ,
        "Abagael"
        ,
        "Abagail"
        ,
        "Abbe"
        ,
        "Abbey"
        ,
        "Abbi"
        ,
        "Abbie"
        ,
        "Abby"
        ,
        "Abbye"
        ,
        "Abigael"
        ,
        "Abigail"
        ,
        "Abigale"
        ,
        "Abra"
        ,
        "Ada"
        ,
        "Adah"
        ,
        "Adaline"
        ,
        "Adan"
        ,
        "Adara"
        ,
        "Adda"
        ,
        "Addi"
        ,
        "Addia"
        ,
        "Addie"
        ,
        "Addy"
        ,
        "Adel"
        ,
        "Adela"
        ,
        "Adelaida"
        ,
        "Adelaide"
        ,
        "Adele"
        ,
        "Adelheid"
        ,
        "Adelice"
        ,
        "Adelina"
        ,
        "Adelind"
        ,
        "Adeline"
        ,
        "Adella"
        ,
        "Adelle"
        ,
        "Adena"
        ,
        "Adey"
        ,
        "Adi"
        ,
        "Adiana"
        ,
        "Adina"
        ,
        "Adora"
        ,
        "Adore"
        ,
        "Adoree"
        ,
        "Adorne"
        ,
        "Adrea"
        ,
        "Adria"
        ,
        "Adriaens"
        ,
        "Adrian"
        ,
        "Adriana"
        ,
        "Adriane"
        ,
        "Adrianna"
        ,
        "Adrianne"
        ,
        "Adriena"
        ,
        "Adrienne"
        ,
        "Aeriel"
        ,
        "Aeriela"
        ,
        "Aeriell"
        ,
        "Afton"
        ,
        "Ag"
        ,
        "Agace"
        ,
        "Agata"
        ,
        "Agatha"
        ,
        "Agathe"
        ,
        "Aggi"
        ,
        "Aggie"
        ,
        "Aggy"
        ,
        "Agna"
        ,
        "Agnella"
        ,
        "Agnes"
        ,
        "Agnese"
        ,
        "Agnesse"
        ,
        "Agneta"
        ,
        "Agnola"
        ,
        "Agretha"
        ,
        "Aida"
        ,
        "Aidan"
        ,
        "Aigneis"
        ,
        "Aila"
        ,
        "Aile"
        ,
        "Ailee"
        ,
        "Aileen"
        ,
        "Ailene"
        ,
        "Ailey"
        ,
        "Aili"
        ,
        "Ailina"
        ,
        "Ailis"
        ,
        "Ailsun"
        ,
        "Ailyn"
        ,
        "Aime"
        ,
        "Aimee"
        ,
        "Aimil"
        ,
        "Aindrea"
        ,
        "Ainslee"
        ,
        "Ainsley"
        ,
        "Ainslie"
        ,
        "Ajay"
        ,
        "Alaine"
        ,
        "Alameda"
        ,
        "Alana"
        ,
        "Alanah"
        ,
        "Alane"
        ,
        "Alanna"
        ,
        "Alayne"
        ,
        "Alberta"
        ,
        "Albertina"
        ,
        "Albertine"
        ,
        "Albina"
        ,
        "Alecia"
        ,
        "Aleda"
        ,
        "Aleece"
        ,
        "Aleen"
        ,
        "Alejandra"
        ,
        "Alejandrina"
        ,
        "Alena"
        ,
        "Alene"
        ,
        "Alessandra"
        ,
        "Aleta"
        ,
        "Alethea"
        ,
        "Alex"
        ,
        "Alexa"
        ,
        "Alexandra"
        ,
        "Alexandrina"
        ,
        "Alexi"
        ,
        "Alexia"
        ,
        "Alexina"
        ,
        "Alexine"
        ,
        "Alexis"
        ,
        "Alfi"
        ,
        "Alfie"
        ,
        "Alfreda"
        ,
        "Alfy"
        ,
        "Ali"
        ,
        "Alia"
        ,
        "Alica"
        ,
        "Alice"
        ,
        "Alicea"
        ,
        "Alicia"
        ,
        "Alida"
        ,
        "Alidia"
        ,
        "Alie"
        ,
        "Alika"
        ,
        "Alikee"
        ,
        "Alina"
        ,
        "Aline"
        ,
        "Alis"
        ,
        "Alisa"
        ,
        "Alisha"
        ,
        "Alison"
        ,
        "Alissa"
        ,
        "Alisun"
        ,
        "Alix"
        ,
        "Aliza"
        ,
        "Alla"
        ,
        "Alleen"
        ,
        "Allegra"
        ,
        "Allene"
        ,
        "Alli"
        ,
        "Allianora"
        ,
        "Allie"
        ,
        "Allina"
        ,
        "Allis"
        ,
        "Allison"
        ,
        "Allissa"
        ,
        "Allix"
        ,
        "Allsun"
        ,
        "Allx"
        ,
        "Ally"
        ,
        "Allyce"
        ,
        "Allyn"
        ,
        "Allys"
        ,
        "Allyson"
        ,
        "Alma"
        ,
        "Almeda"
        ,
        "Almeria"
        ,
        "Almeta"
        ,
        "Almira"
        ,
        "Almire"
        ,
        "Aloise"
        ,
        "Aloisia"
        ,
        "Aloysia"
        ,
        "Alta"
        ,
        "Althea"
        ,
        "Alvera"
        ,
        "Alverta"
        ,
        "Alvina"
        ,
        "Alvinia"
        ,
        "Alvira"
        ,
        "Alyce"
        ,
        "Alyda"
        ,
        "Alys"
        ,
        "Alysa"
        ,
        "Alyse"
        ,
        "Alysia"
        ,
        "Alyson"
        ,
        "Alyss"
        ,
        "Alyssa"
        ,
        "Amabel"
        ,
        "Amabelle"
        ,
        "Amalea"
        ,
        "Amalee"
        ,
        "Amaleta"
        ,
        "Amalia"
        ,
        "Amalie"
        ,
        "Amalita"
        ,
        "Amalle"
        ,
        "Amanda"
        ,
        "Amandi"
        ,
        "Amandie"
        ,
        "Amandy"
        ,
        "Amara"
        ,
        "Amargo"
        ,
        "Amata"
        ,
        "Amber"
        ,
        "Amberly"
        ,
        "Ambur"
        ,
        "Ame"
        ,
        "Amelia"
        ,
        "Amelie"
        ,
        "Amelina"
        ,
        "Ameline"
        ,
        "Amelita"
        ,
        "Ami"
        ,
        "Amie"
        ,
        "Amii"
        ,
        "Amil"
        ,
        "Amitie"
        ,
        "Amity"
        ,
        "Ammamaria"
        ,
        "Amy"
        ,
        "Amye"
        ,
        "Ana"
        ,
        "Anabal"
        ,
        "Anabel"
        ,
        "Anabella"
        ,
        "Anabelle"
        ,
        "Analiese"
        ,
        "Analise"
        ,
        "Anallese"
        ,
        "Anallise"
        ,
        "Anastasia"
        ,
        "Anastasie"
        ,
        "Anastassia"
        ,
        "Anatola"
        ,
        "Andee"
        ,
        "Andeee"
        ,
        "Anderea"
        ,
        "Andi"
        ,
        "Andie"
        ,
        "Andra"
        ,
        "Andrea"
        ,
        "Andreana"
        ,
        "Andree"
        ,
        "Andrei"
        ,
        "Andria"
        ,
        "Andriana"
        ,
        "Andriette"
        ,
        "Andromache"
        ,
        "Andy"
        ,
        "Anestassia"
        ,
        "Anet"
        ,
        "Anett"
        ,
        "Anetta"
        ,
        "Anette"
        ,
        "Ange"
        ,
        "Angel"
        ,
        "Angela"
        ,
        "Angele"
        ,
        "Angelia"
        ,
        "Angelica"
        ,
        "Angelika"
        ,
        "Angelina"
        ,
        "Angeline"
        ,
        "Angelique"
        ,
        "Angelita"
        ,
        "Angelle"
        ,
        "Angie"
        ,
        "Angil"
        ,
        "Angy"
        ,
        "Ania"
        ,
        "Anica"
        ,
        "Anissa"
        ,
        "Anita"
        ,
        "Anitra"
        ,
        "Anjanette"
        ,
        "Anjela"
        ,
        "Ann"
        ,
        "Ann-Marie"
        ,
        "Anna"
        ,
        "Anna-Diana"
        ,
        "Anna-Diane"
        ,
        "Anna-Maria"
        ,
        "Annabal"
        ,
        "Annabel"
        ,
        "Annabela"
        ,
        "Annabell"
        ,
        "Annabella"
        ,
        "Annabelle"
        ,
        "Annadiana"
        ,
        "Annadiane"
        ,
        "Annalee"
        ,
        "Annaliese"
        ,
        "Annalise"
        ,
        "Annamaria"
        ,
        "Annamarie"
        ,
        "Anne"
        ,
        "Anne-Corinne"
        ,
        "Anne-Marie"
        ,
        "Annecorinne"
        ,
        "Anneliese"
        ,
        "Annelise"
        ,
        "Annemarie"
        ,
        "Annetta"
        ,
        "Annette"
        ,
        "Anni"
        ,
        "Annice"
        ,
        "Annie"
        ,
        "Annis"
        ,
        "Annissa"
        ,
        "Annmaria"
        ,
        "Annmarie"
        ,
        "Annnora"
        ,
        "Annora"
        ,
        "Anny"
        ,
        "Anselma"
        ,
        "Ansley"
        ,
        "Anstice"
        ,
        "Anthe"
        ,
        "Anthea"
        ,
        "Anthia"
        ,
        "Anthiathia"
        ,
        "Antoinette"
        ,
        "Antonella"
        ,
        "Antonetta"
        ,
        "Antonia"
        ,
        "Antonie"
        ,
        "Antonietta"
        ,
        "Antonina"
        ,
        "Anya"
        ,
        "Appolonia"
        ,
        "April"
        ,
        "Aprilette"
        ,
        "Ara"
        ,
        "Arabel"
        ,
        "Arabela"
        ,
        "Arabele"
        ,
        "Arabella"
        ,
        "Arabelle"
        ,
        "Arda"
        ,
        "Ardath"
        ,
        "Ardeen"
        ,
        "Ardelia"
        ,
        "Ardelis"
        ,
        "Ardella"
        ,
        "Ardelle"
        ,
        "Arden"
        ,
        "Ardene"
        ,
        "Ardenia"
        ,
        "Ardine"
        ,
        "Ardis"
        ,
        "Ardisj"
        ,
        "Ardith"
        ,
        "Ardra"
        ,
        "Ardyce"
        ,
        "Ardys"
        ,
        "Ardyth"
        ,
        "Aretha"
        ,
        "Ariadne"
        ,
        "Ariana"
        ,
        "Aridatha"
        ,
        "Ariel"
        ,
        "Ariela"
        ,
        "Ariella"
        ,
        "Arielle"
        ,
        "Arlana"
        ,
        "Arlee"
        ,
        "Arleen"
        ,
        "Arlen"
        ,
        "Arlena"
        ,
        "Arlene"
        ,
        "Arleta"
        ,
        "Arlette"
        ,
        "Arleyne"
        ,
        "Arlie"
        ,
        "Arliene"
        ,
        "Arlina"
        ,
        "Arlinda"
        ,
        "Arline"
        ,
        "Arluene"
        ,
        "Arly"
        ,
        "Arlyn"
        ,
        "Arlyne"
        ,
        "Aryn"
        ,
        "Ashely"
        ,
        "Ashia"
        ,
        "Ashien"
        ,
        "Ashil"
        ,
        "Ashla"
        ,
        "Ashlan"
        ,
        "Ashlee"
        ,
        "Ashleigh"
        ,
        "Ashlen"
        ,
        "Ashley"
        ,
        "Ashli"
        ,
        "Ashlie"
        ,
        "Ashly"
        ,
        "Asia"
        ,
        "Astra"
        ,
        "Astrid"
        ,
        "Astrix"
        ,
        "Atalanta"
        ,
        "Athena"
        ,
        "Athene"
        ,
        "Atlanta"
        ,
        "Atlante"
        ,
        "Auberta"
        ,
        "Aubine"
        ,
        "Aubree"
        ,
        "Aubrette"
        ,
        "Aubrey"
        ,
        "Aubrie"
        ,
        "Aubry"
        ,
        "Audi"
        ,
        "Audie"
        ,
        "Audra"
        ,
        "Audre"
        ,
        "Audrey"
        ,
        "Audrie"
        ,
        "Audry"
        ,
        "Audrye"
        ,
        "Audy"
        ,
        "Augusta"
        ,
        "Auguste"
        ,
        "Augustina"
        ,
        "Augustine"
        ,
        "Aundrea"
        ,
        "Aura"
        ,
        "Aurea"
        ,
        "Aurel"
        ,
        "Aurelea"
        ,
        "Aurelia"
        ,
        "Aurelie"
        ,
        "Auria"
        ,
        "Aurie"
        ,
        "Aurilia"
        ,
        "Aurlie"
        ,
        "Auroora"
        ,
        "Aurora"
        ,
        "Aurore"
        ,
        "Austin"
        ,
        "Austina"
        ,
        "Austine"
        ,
        "Ava"
        ,
        "Aveline"
        ,
        "Averil"
        ,
        "Averyl"
        ,
        "Avie"
        ,
        "Avis"
        ,
        "Aviva"
        ,
        "Avivah"
        ,
        "Avril"
        ,
        "Avrit"
        ,
        "Ayn"
        ,
        "Bab"
        ,
        "Babara"
        ,
        "Babb"
        ,
        "Babbette"
        ,
        "Babbie"
        ,
        "Babette"
        ,
        "Babita"
        ,
        "Babs"
        ,
        "Bambi"
        ,
        "Bambie"
        ,
        "Bamby"
        ,
        "Barb"
        ,
        "Barbabra"
        ,
        "Barbara"
        ,
        "Barbara-Anne"
        ,
        "Barbaraanne"
        ,
        "Barbe"
        ,
        "Barbee"
        ,
        "Barbette"
        ,
        "Barbey"
        ,
        "Barbi"
        ,
        "Barbie"
        ,
        "Barbra"
        ,
        "Barby"
        ,
        "Bari"
        ,
        "Barrie"
        ,
        "Barry"
        ,
        "Basia"
        ,
        "Bathsheba"
        ,
        "Batsheva"
        ,
        "Bea"
        ,
        "Beatrice"
        ,
        "Beatrisa"
        ,
        "Beatrix"
        ,
        "Beatriz"
        ,
        "Bebe"
        ,
        "Becca"
        ,
        "Becka"
        ,
        "Becki"
        ,
        "Beckie"
        ,
        "Becky"
        ,
        "Bee"
        ,
        "Beilul"
        ,
        "Beitris"
        ,
        "Bekki"
        ,
        "Bel"
        ,
        "Belia"
        ,
        "Belicia"
        ,
        "Belinda"
        ,
        "Belita"
        ,
        "Bell"
        ,
        "Bella"
        ,
        "Bellanca"
        ,
        "Belle"
        ,
        "Bellina"
        ,
        "Belva"
        ,
        "Belvia"
        ,
        "Bendite"
        ,
        "Benedetta"
        ,
        "Benedicta"
        ,
        "Benedikta"
        ,
        "Benetta"
        ,
        "Benita"
        ,
        "Benni"
        ,
        "Bennie"
        ,
        "Benny"
        ,
        "Benoite"
        ,
        "Berenice"
        ,
        "Beret"
        ,
        "Berget"
        ,
        "Berna"
        ,
        "Bernadene"
        ,
        "Bernadette"
        ,
        "Bernadina"
        ,
        "Bernadine"
        ,
        "Bernardina"
        ,
        "Bernardine"
        ,
        "Bernelle"
        ,
        "Bernete"
        ,
        "Bernetta"
        ,
        "Bernette"
        ,
        "Berni"
        ,
        "Bernice"
        ,
        "Bernie"
        ,
        "Bernita"
        ,
        "Berny"
        ,
        "Berri"
        ,
        "Berrie"
        ,
        "Berry"
        ,
        "Bert"
        ,
        "Berta"
        ,
        "Berte"
        ,
        "Bertha"
        ,
        "Berthe"
        ,
        "Berti"
        ,
        "Bertie"
        ,
        "Bertina"
        ,
        "Bertine"
        ,
        "Berty"
        ,
        "Beryl"
        ,
        "Beryle"
        ,
        "Bess"
        ,
        "Bessie"
        ,
        "Bessy"
        ,
        "Beth"
        ,
        "Bethanne"
        ,
        "Bethany"
        ,
        "Bethena"
        ,
        "Bethina"
        ,
        "Betsey"
        ,
        "Betsy"
        ,
        "Betta"
        ,
        "Bette"
        ,
        "Bette-Ann"
        ,
        "Betteann"
        ,
        "Betteanne"
        ,
        "Betti"
        ,
        "Bettina"
        ,
        "Bettine"
        ,
        "Betty"
        ,
        "Bettye"
        ,
        "Beulah"
        ,
        "Bev"
        ,
        "Beverie"
        ,
        "Beverlee"
        ,
        "Beverley"
        ,
        "Beverlie"
        ,
        "Beverly"
        ,
        "Bevvy"
        ,
        "Bianca"
        ,
        "Bianka"
        ,
        "Bibbie"
        ,
        "Bibby"
        ,
        "Bibbye"
        ,
        "Bibi"
        ,
        "Biddie"
        ,
        "Biddy"
        ,
        "Bidget"
        ,
        "Bili"
        ,
        "Bill"
        ,
        "Billi"
        ,
        "Billie"
        ,
        "Billy"
        ,
        "Billye"
        ,
        "Binni"
        ,
        "Binnie"
        ,
        "Binny"
        ,
        "Bird"
        ,
        "Birdie"
        ,
        "Birgit"
        ,
        "Birgitta"
        ,
        "Blair"
        ,
        "Blaire"
        ,
        "Blake"
        ,
        "Blakelee"
        ,
        "Blakeley"
        ,
        "Blanca"
        ,
        "Blanch"
        ,
        "Blancha"
        ,
        "Blanche"
        ,
        "Blinni"
        ,
        "Blinnie"
        ,
        "Blinny"
        ,
        "Bliss"
        ,
        "Blisse"
        ,
        "Blithe"
        ,
        "Blondell"]
aome=['ade','yosola','align','Willia','Abisade','aliyu','risikat','rahmanfire']
CHAR = "qwertyuipoiuytrwertkjhgfdzxcvbnm"
data={}
driver = Chrome('chromedriver.exe')
wait=WebDriverWait(driver,10)
def generate_details():
    print("Starting program")
    data['username']="__".join( ["".join(random.sample(aome,3)) ,"".join(random.sample(CHAR,3)) ])
    data['email'] =data['username'] + "@yahoo.com"
    data['password']="P@ssword123*"
    data['fullname']=" ".join(data['username'].split('_'))

def main():
    generate_details()
    driver.get('https://instagram.com')
    driver.find_element_by_name('emailOrPhone').send_keys(data['email'].lower())
    sleep(1)
    driver.find_element_by_name('fullName').send_keys(data['fullname'])
    sleep(1)
    driver.find_element_by_name('username').send_keys(data['username'].lower())
    sleep(1)
    driver.find_element_by_name('password').send_keys(data['password'])
    sleep(1)
    print("Details updated \n Using: ")
    pprint(data)
    # submit registration
    btn = driver.find_elements_by_tag_name('button')
    sign_up = next((x for x in btn if x.text == "Sign up"), None)
    print("Signing Up")
    sign_up.click()
    sleep(4)
    try:
        sign_up.click()
    except WebDriverException:
        sleep(3)
        sign_up.click()
    sleep(5)
    suggested_follow = WebDriverWait(driver, 5).until(EC.text_to_be_present_in_element((By.TAG_NAME,'button'),'Follow')) #driver.find_elements_by_tag_name('button')
    if suggested_follow is not None:
        suggested_follow=driver.find_elements_by_tag_name('button')
        print([a.text for a in suggested_follow])
        print("Cancelling desktop notifications")
        suggested_follow[-1].click()
        print("Following a couple of users")
        for a in suggested_follow[:3]:
            a.click()
            sleep(1)
        # Navigate to the instagram post
        sleep(2)
        print("Navigatign to the post")
        driver.get("https://www.instagram.com/p/BsDyat2nqGs/?utm_source=ig_share_sheet&igshid=11or250k6ofxv")
        # Play video
        print("Trying to play video")
        sleep(5)
        element = WebDriverWait(driver, 5).until(
            EC.visibility_of_element_located((By.TAG_NAME,'video')))
        if element:
            # driver.execute_script('document.getElementsByTagName("video")[0].play()')
            pass
        # Like Video

        print('Liking video')
        btn = driver.find_element_by_xpath("//span[@class='fr66n']/button").click()
        # Comment
        print("Commenting Yes!!")
        # element = WebDriverWait(driver, 5).until(
        #     EC.presence_of_element_located((By.XPATH, "//textarea[@class='Ypffh'")))
        # element.send_keys("Yes")
        # # Type Enter
        # element.send_keys(Keys.ENTER)
        print('Success')
        print("Closing this account")
        driver.quit()

if __name__ == '__main__':
    while True:
        try:
            main()
        except Exception:
            driver.quit()
            driver.close()
        except StaleElementReferenceException:
            driver.quit()
            driver.close()
        except TimeoutException:
            driver.quit()
            driver.close()
        finally:
            driver=Chrome()
            main()



# try:
#     main()
# except Exception as e:
#     driver.close()
#     print("Failed")
#     print(e)